# Numpy 
(Numerical Python)

Principais recursos:
- Poderoso objeto array multidimensional.
- Funções matemáticas sofisticadas para operações com arrays, sem uso de laços for.
- Recursos de álgebra linear e geração de números aleatórios.

Documentação: https://numpy.org/doc/1.24

In [1]:
# Importando o Numpy
import numpy as np

In [2]:
# Criando um array Numpy
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Importando parte do pacote:
from numpy import arange

In [ ]:
arange(20)

In [3]:
# Criando arrays a partir de lista:
numeros = np.array([100, 988, 345, 1200])

In [4]:
numeros

array([ 100,  988,  345, 1200])

In [5]:
type(numeros)

numpy.ndarray

In [6]:
# Tipos de dados do Numpy
numeros.dtype

dtype('int32')

In [7]:
# Carregando dados externos com o Numpy:
teste = np.loadtxt(fname = 'teste_num.txt', dtype = int)

In [8]:
teste

array([ 10, 123,  30,  45,  68, 321])

In [9]:
teste.dtype

dtype('int32')

In [10]:
# Array de duas dimensões (Matrizes e Datasets)
dados = [
    ['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Bahia'],
    ['Paraná', 'Santa Catarina', 'Rio Grande do Sul', 'Espírito Santo'],
    ['Ceará', 'Bahia', 'Maranhão', 'Alagoas']
]

In [11]:
dados

[['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Bahia'],
 ['Paraná', 'Santa Catarina', 'Rio Grande do Sul', 'Espírito Santo'],
 ['Ceará', 'Bahia', 'Maranhão', 'Alagoas']]

In [12]:
estados = np.array(dados)

In [13]:
estados

array([['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Bahia'],
       ['Paraná', 'Santa Catarina', 'Rio Grande do Sul',
        'Espírito Santo'],
       ['Ceará', 'Bahia', 'Maranhão', 'Alagoas']], dtype='<U17')

In [14]:
type(estados)

numpy.ndarray

In [15]:
estados.shape

(3, 4)

In [16]:
# Comparando desempenho do Numpy e listas
np_array = np.arange(2000000)

In [17]:
py_list = list(range(2000000))

In [18]:
%time for _ in range(100): np_array *= 2

CPU times: total: 125 ms
Wall time: 169 ms


In [19]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: total: 21.7 s
Wall time: 21.7 s
